services:
    # Path manager
    innova_path.manager.path:
        class: %innova_path.manager.path.class%
        arguments:
            objectManager:   @doctrine.orm.entity_manager
            securityAuth:    @security.authorization_checker
            securityToken:   @security.token_storage
            resourceManager: @claroline.manager.resource_manager
            utils:           @claroline.security.utilities
            stepManager:     @innova_path.manager.step

    # Publishing manager
    innova_path.manager.publishing:
        class: %innova_path.manager.publishing.class%
        arguments:
            objectManager: @doctrine.orm.entity_manager
            stepManager:   @innova_path.manager.step
            rightsManager: @claroline.manager.rights_manager

    # Path template manager
    innova_path.manager.path_template:
        class: %innova_path.manager.path_template.class%
        arguments:
            objectManager: @doctrine.orm.entity_manager

    # Step manager
    innova_path.manager.step:
        class: %innova_path.manager.step.class%
        arguments:
            om:              @doctrine.orm.entity_manager
            resourceManager: @claroline.manager.resource_manager
            session:         @session
            translator:      @translator
            container:       @service_container
            maskManager:     @claroline.manager.mask_manager

    # User Progression manager
    innova_path.manager.user_progression:
        class: %innova_path.manager.user_progression.class%
        arguments:
            objectManager: @doctrine.orm.entity_manager
            securityToken: @security.token_storage
